name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-deph: 0

    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build docker image
      run: |
        docker build -t pedrobiel/docker-graphql:0.0.2 .
        docker build -t pedrobiel/docker-graphql:latest .

    - name: Push docker image
      run: |
        docker push pedrobiel/docker-graphql:0.0.2
        docker push pedrobiel/docker-graphql:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
